import { createGlobalStyle } from "styled-components";

export default createGlobalStyle`
  *,
  *::before,
  *::after {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    background-color: transparent;
  }

  body {
    margin: 0;
    font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
  }
`;
/* original style theme {
  --color-black: #000;
  --color-gray-light: #EEE;
  --color-white: #FFF;
  --color-red: #F03;
  --color-text: #333;
  --color-title-underline: #D5D5D5;
  --color-radical: #00AAFF;
  --color-radical-dark: #0093DD;
  --color-radical-highlight: #88d7ff;
  --color-radical-lowlight: #069;
  --color-radical-gradient: var(--color-radical), var(--color-radical-dark);
  --color-kanji: #FF00AA;
  --color-kanji-dark: #FF00AA;
  --color-kanji-highlight: #f6c;
  --color-kanji-lowlight: #cc0088;
  --color-kanji-gradient: var(--color-kanji), var(--color-kanji-dark);
  --color-vocabulary: #AA00FF;
  --color-vocabulary-dark: #AA00FF;
  --color-vocabulary-highlight: #c655ff;
  --color-vocabulary-lowlight: #8800cc;
  --color-vocabulary-gradient: var(--color-vocabulary), var(--color-vocabulary-dark);
  --color-subject-slide-navigation-background: #252A3A;
  --color-subject-slide-navigation-text: var(--color-white, #FFF);
  --color-subject-slide-navigation-button-hover: var(--color-gray-light);
  --color-modal-mask: rgba(0,0,0,0.8);
  --color-modal-background: var(--color-gray-light);
  --color-lesson-modal-text: #FFF;
  --color-button-default-background: transparent;
  --color-button-default-border: #BBB;
  --color-button-default-text: #555;
  --color-button-default-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-default-hover-background: transparent;
  --color-button-default-hover-border: #888;
  --color-button-default-hover-text: #333;
  --color-button-default-hover-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-default-active-background: #88888820;
  --color-button-default-active-border: #888;
  --color-button-default-active-text: #333;
  --color-button-default-active-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-icon-only-background: transparent;
  --color-button-icon-only-border: transparent;
  --color-button-icon-only-text: #555;
  --color-button-icon-only-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-icon-only-hover-background: #88888820;
  --color-button-icon-only-hover-border: transparent;
  --color-button-icon-only-hover-text: #333;
  --color-button-icon-only-hover-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-icon-only-active-background: #88888840;
  --color-button-icon-only-active-border: transparent;
  --color-button-icon-only-active-text: #333;
  --color-button-icon-only-active-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-quiz-background: #34D399;
  --color-button-quiz-text: var(--color-white);
  --color-button-quiz-text-shadow: 0 1px 0 var(--color-text-shadow-dark);
  --color-button-modal-primary-background: #FFF;
  --color-button-modal-primary-border: #FFF;
  --color-button-modal-primary-text: var(--color-black);
  --color-button-modal-primary-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-modal-primary-hover-background: #FFF;
  --color-button-modal-primary-hover-border: #FFF;
  --color-button-modal-primary-hover-text: var(--color-black);
  --color-button-modal-primary-hover-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-modal-primary-active-background: #FFF;
  --color-button-modal-primary-active-border: #FFF;
  --color-button-modal-primary-active-text: var(--color-black);
  --color-button-modal-primary-active-text-shadow: 0 1px 0 var(--color-text-shadow-light);
  --color-button-modal-secondary-background: transparent;
  --color-button-modal-secondary-border: #FFF;
  --color-button-modal-secondary-text: #FFF;
  --color-button-modal-secondary-text-shadow: 0 1px 0 var(--color-text-shadow-dark);
  --color-button-modal-secondary-hover-background: transparent;
  --color-button-modal-secondary-hover-border: #FFF;
  --color-button-modal-secondary-hover-text: #FFF;
  --color-button-modal-secondary-hover-text-shadow: 0 1px 0 var(--color-text-shadow-dark);
  --color-button-modal-secondary-active-background: #FFFFFF80;
  --color-button-modal-secondary-active-border: #FFF;
  --color-button-modal-secondary-active-text: #FFF;
  --color-button-modal-secondary-active-text-shadow: 0 1px 0 var(--color-text-shadow-dark);
  --color-button-synonym-background: #E1E1E1;
  --color-button-synonym-border: transparent;
  --color-button-synonym-text: #333;
  --color-button-synonym-text-shadow: var(--text-shadow-light);
  --color-button-synonym-hover-background: #555555;
  --color-button-synonym-hover-border: transparent;
  --color-button-synonym-hover-text: #FFF;
  --color-button-synonym-hover-text-shadow: var(--text-shadow-dark);
  --color-button-synonym-active-background: #333;
  --color-button-synonym-active-border: transparent;
  --color-button-synonym-active-text: #FFF;
  --color-button-synonym-active-text-shadow: var(--text-shadow-dark);
  --color-button-blocked-synonym-background: #DD9B9B;
  --color-button-blocked-synonym-border: transparent;
  --color-button-blocked-synonym-text: #333;
  --color-button-blocked-synonym-text-shadow: 0 1px 0 #FFFFFF80;
  --color-button-blocked-synonym-hover-background: #DD5050;
  --color-button-blocked-synonym-hover-border: transparent;
  --color-button-blocked-synonym-hover-text: #FFF;
  --color-button-blocked-synonym-hover-text-shadow: var(--text-shadow-dark);
  --color-button-blocked-synonym-active-background: #DE1B1B;
  --color-button-blocked-synonym-active-border: transparent;
  --color-button-blocked-synonym-active-text: #FFF;
  --color-button-blocked-synonym-active-text-shadow: var(--text-shadow-dark);
  --color-form-error-text: #B94A48;
  --color-form-error-background: #DD9B9B;
  --color-form-error-text-shadow: #FFFFFF80;
  --color-hint-text: #666;
  --color-hint-title: #555;
  --color-hint-background: #e6e6e6;
  --color-input-text: var(--color-text);
  --color-input-background: #FFF;
  --color-input-border: #BBB;
  --color-input-focus-border: var(--color-radical);
  --color-text-shadow-dark: rgba(0, 0, 0, 0.2);
  --color-text-shadow-light: #FFF;
  --color-quiz-input-background: #FFF;
  --color-quiz-input-focus: #B7E0F4;
  --color-quiz-incorrect-background: #F03;
  --color-quiz-incorrect-text-color: var(--color-white);
  --color-quiz-incorrect-text-shadow: 1px 1px 0 var(--color-text-shadow-dark);
  --color-quiz-correct-background: #88cc00;
  --color-quiz-correct-text-color: var(--color-white);
  --color-quiz-correct-text-shadow: 1px 1px 0 var(--color-text-shadow-dark);
  --color-quiz-srs-correct-background: #39aa0b;
  --color-quiz-srs-correct-text-color: var(--color-white);
  --color-quiz-srs-correct-text-shadow: 1px 1px 0 var(--color-text-shadow-dark);
  --color-quiz-srs-incorrect-background: var(--color-red);
  --color-quiz-srs-incorrect-text-color: var(--color-white);
  --color-quiz-srs-incorrect-text-shadow: 1px 1px 0 var(--color-text-shadow-dark);
  --color-synonym-blocked: #DD5252;
  --color-dashboard-panel-background: #F4F4F4;
  --color-dashboard-panel-content-background: #FFF;
} */
